---
title: "an awesome title"
date: 2018-08-27
author: Eric S
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
---
